[[redirects]]
from = "/about"
to = "/index.html"
status = 200

[[redirects]]
from = "/explore-future"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://oct-n-shrk.studio/"
status = 301